services:

  iac:
    image: mcr.microsoft.com/devcontainers/base:dev-debian-13
    command: sleep infinity
    container_name: terrafor
    volumes:
      - ../../..:/workspaces:cached

  localstack:
    image: localstack/localstack:4.10.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"